### PR TITLE
Replaced Agent treatment for Env4InRow

### PR DESCRIPTION
**Pull request by levzlotnik**
* Added treatment for `Agent` objects
* Added support for switching turns
* Changed main.py accordingly
* Added `__hash__` and `__eq__` in `Agent` to allow using agents as keys to dictionaries
* Refactored code - added more "pythonic" code style (using dictionaries instead of if-else cases)
* Added a `'pass'` action treatment in Env4InRow
* Removed redundant for loops in `main.py`

### CODE REVIEW

**Comment by levzlotnik** [comment]
Please review my code - I added some more "pythonic" code styling

**Review by David6114 — COMMENTED** [review]
OK

**Comment by levzlotnik** [comment]
Will resolve conflicts in a moment

**Review by nabaco — COMMENTED** [review]
Add a test in the first test function for an illegal move for each player

**Pull request merged**
