### PR TITLE
 Fixed imports issue in tests file

### PR DESCRIPTION
**Pull request by nabaco**
Fixed imports issue in the tests file, by turning the tests/ folder into a module with __init__.py.
Removed unnecessary lines from top __init__.py file.

### CODE REVIEW

**Comment by nabaco** [comment]
CI is failing, while on my setup it works, seems like environment differences:
**Travis:**
- pip 19.0.3 
- Python 3.6.7
- pytest-4.3.1
- py-1.7.0
- pluggy-0.8.0
- linux (Xenial)

**Nachum:**
- pip 9.0.1
- Python 3.6.2
- pytest-5.0.1
- linux (Trusty)

**Review by levzlotnik — CHANGES_REQUESTED** [review]
I don't know why it doesn't work on xenial, but it's the newer version so we have to get it to work on it...

**Comment by nabaco** [comment]
- pip 9.0.1
- Python 3.6.3
- pytest-3.3.0
- py-1.5.2
- pluggy-0.6.0
- linux (trusty)

still fails..

**Comment by nabaco** [comment]
for reference sake:
http://doc.pytest.org/en/latest/goodpractices.html

**Review by levzlotnik — APPROVED** [review]

**Pull request merged**
